### ISSUE TITLE
Dashboard not working with sql_mode=only_full_group_by

### ISSUE THREAD

**Issue by mikeb93** [Icinga/icingaweb2-module-x509#8]
## Expected Behavior

Dashboard is accessible

## Current Behavior

Dashboard will throw an exception. At the top the following message will appear:
`SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'x509.c.issuer' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

## Possible Solution

Remove  ONLY_FULL_GROUP_BY from mysql:
`SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`

For permanently disabling the mode:

```
vim /etc/mysql/mysql.conf.d/mysqld.cnf
[mysqld]
sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
```

systemctl restart mysql

## Steps to Reproduce (for bugs)

1. Install default mysql server > 5.7 on Ubuntu Server 18.04.1 LTS
2. Install the module (following the instructions)
3. Access the Dashboard

## Your Environment

* Module version (System - About): Master
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): 2.10.2
* Operating System and version: Ubuntu Server 18.04.1 LTS

Maybe add this to the install instructions

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Could you please test the related PR?
I fixed the queries plus we now set the MySQL 8 default SQL modes explicitly on a per connection basis, including ONLY_FULL_GROUP_BY because they're sane.

Best,
Eric

**Comment by mikeb93** [comment]
I just tested without setting the sql_mode as mentioned in the issue. I still get the same error

**Comment by lippserd** [comment]
How did you test the PR? If you have a git installation the easiest way would be:

`git fetch && git checkout -b fix/sql-mode-full-group-by origin/fix/sql-mode-full-group-by`

**Comment by mikeb93** [comment]
Sorry my mistake, I just pulled the master and didn't check for a new branch.
Seems to work with the fix. All good now :)
Thanks

**Comment by the-r0cket06** [comment]
I had the same issue, and pulling this branch resolved it for me as well.
Thanks,
